name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn lint
      - run: yarn test
